-- --------------------------------------------------------
-- Servidor:                     127.0.0.1
-- Versão do servidor:           5.7.14 - MySQL Community Server (GPL)
-- OS do Servidor:               Win32
-- HeidiSQL Versão:              9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Copiando estrutura do banco de dados para db_4events
CREATE DATABASE IF NOT EXISTS `db_4events` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `db_4events`;


-- Copiando estrutura para tabela db_4events.paises
CREATE TABLE IF NOT EXISTS `paises` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sigla` varchar(2) DEFAULT NULL,
  `nome` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=251 DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela db_4events.paises: 0 rows
/*!40000 ALTER TABLE `paises` DISABLE KEYS */;
REPLACE INTO `paises` (`id`, `sigla`, `nome`) VALUES
	(1, 'AF', 'Afeganistão'),
	(2, 'AL', 'Albânia'),
	(3, 'DE', 'Alemanha'),
	(4, 'AD', 'Andorra'),
	(5, 'AO', 'Angola'),
	(6, 'AI', 'Anguilla'),
	(7, 'AG', 'Antigua e Barbuda'),
	(8, 'AN', 'Antilhas Holandesas'),
	(9, 'AQ', 'Antártica'),
	(10, 'AR', 'Argentina'),
	(11, 'DZ', 'Argélia'),
	(12, 'AM', 'Armênia'),
	(13, 'AW', 'Aruba'),
	(14, 'SA', 'Arábia Saudita'),
	(15, 'AU', 'Austrália'),
	(16, 'AZ', 'Azerbaijão'),
	(17, 'BS', 'Bahamas'),
	(18, 'BH', 'Bahrein'),
	(19, 'BD', 'Bangladesh'),
	(20, 'BB', 'Barbados'),
	(21, 'BZ', 'Belize'),
	(22, 'BJ', 'Benin'),
	(23, 'BM', 'Bermuda'),
	(24, 'BY', 'Bielorrússia'),
	(25, 'BO', 'Bolívia'),
	(26, 'BW', 'Botsuana'),
	(27, 'BR', 'Brasil'),
	(28, 'BN', 'Brunei'),
	(29, 'BG', 'Bulgária'),
	(30, 'BF', 'Burkina Faso'),
	(31, 'BI', 'Burundi'),
	(32, 'BT', 'Butão'),
	(33, 'BE', 'Bélgica'),
	(34, 'BA', 'Bósnia e Herzegovina'),
	(35, 'CV', 'Cabo Verde'),
	(36, 'CM', 'Camarões'),
	(37, 'KH', 'Camboja'),
	(38, 'CA', 'Canadá'),
	(39, 'BQ', 'Caribbean Netherlands'),
	(40, 'KZ', 'Cazaquistão'),
	(41, 'TD', 'Chade'),
	(42, 'CL', 'Chile'),
	(43, 'CN', 'China'),
	(44, 'CY', 'Chipre'),
	(45, 'SG', 'Cingapura'),
	(46, 'CO', 'Colômbia'),
	(47, 'KM', 'Comores'),
	(48, 'CG', 'Congo (Brazzaville)'),
	(49, 'CD', 'Congo (Kinshasa)'),
	(50, 'KP', 'Coréia do Norte'),
	(51, 'KR', 'Coréia do Sul'),
	(52, 'CI', 'Costa do Marfim'),
	(53, 'CR', 'Costa Rica'),
	(54, 'HR', 'Croácia'),
	(55, 'CU', 'Cuba'),
	(56, 'CW', 'Curaçao'),
	(57, 'DK', 'Dinamarca'),
	(58, 'DJ', 'Djibuti'),
	(59, 'DM', 'Dominica'),
	(60, 'EG', 'Egito'),
	(61, 'SV', 'El Salvador'),
	(62, 'AE', 'Emirados Árabes Unidos'),
	(63, 'EC', 'Equador'),
	(64, 'ER', 'Eritréia'),
	(65, 'SK', 'Eslováquia'),
	(66, 'SI', 'Eslovênia'),
	(67, 'ES', 'Espanha'),
	(68, 'US', 'Estados Unidos'),
	(69, 'EE', 'Estônia'),
	(70, 'ET', 'Etiópia'),
	(71, 'FJ', 'Fiji'),
	(72, 'PH', 'Filipinas'),
	(73, 'FI', 'Finlândia'),
	(74, 'FR', 'França'),
	(75, 'GA', 'Gabão'),
	(76, 'GH', 'Gana'),
	(77, 'GE', 'Geórgia'),
	(78, 'GI', 'Gibraltar'),
	(79, 'GD', 'Granada'),
	(80, 'GL', 'Groenlândia'),
	(81, 'GR', 'Grécia'),
	(82, 'GP', 'Guadalupe'),
	(83, 'GU', 'Guam'),
	(84, 'GT', 'Guatemala'),
	(85, 'GG', 'Guernsey'),
	(86, 'GY', 'Guiana'),
	(87, 'GF', 'Guiana Francesa'),
	(88, 'GN', 'Guiné'),
	(89, 'GW', 'Guiné-Bissau'),
	(90, 'GQ', 'Guiné Equatorial'),
	(91, 'GM', 'Gâmbia'),
	(92, 'HT', 'Haiti'),
	(93, 'NL', 'Holanda'),
	(94, 'HN', 'Honduras'),
	(95, 'HK', 'Hong Kong, China'),
	(96, 'HU', 'Hungria'),
	(97, 'BV', 'Ilha Bouvet'),
	(98, 'CX', 'Ilha Christmas'),
	(99, 'IM', 'Ilha de Man'),
	(100, 'HM', 'Ilha Heard e Ilhas McDonald'),
	(101, 'NF', 'Ilha Norfolk'),
	(102, 'AX', 'Ilhas Aland'),
	(103, 'KY', 'Ilhas Cayman'),
	(104, 'CC', 'Ilhas Cocos'),
	(105, 'CK', 'Ilhas Cook'),
	(106, 'FK', 'Ilhas Falkland'),
	(107, 'FO', 'Ilhas Faroe'),
	(108, 'GS', 'Ilhas Geórgia do Sul e Sandwich do Sul'),
	(109, 'MP', 'Ilhas Marianas do Norte'),
	(110, 'MH', 'Ilhas Marshall'),
	(111, 'SB', 'Ilhas Salomão'),
	(112, 'TC', 'Ilhas Turcas e Caicos'),
	(113, 'VI', 'Ilhas Virgens Americanas'),
	(114, 'VG', 'Ilhas Virgens Britânicas'),
	(115, 'ID', 'Indonésia'),
	(116, 'IQ', 'Iraque'),
	(117, 'IE', 'Irlanda'),
	(118, 'IR', 'Irã'),
	(119, 'IS', 'Islândia'),
	(120, 'IL', 'Israel'),
	(121, 'IT', 'Itália'),
	(122, 'YE', 'Iêmen'),
	(123, 'JM', 'Jamaica'),
	(124, 'JP', 'Japão'),
	(125, 'JE', 'Jersey'),
	(126, 'JO', 'Jordânia'),
	(127, 'KI', 'Kiribati'),
	(128, 'KW', 'Kuwait'),
	(129, 'LA', 'Laos'),
	(130, 'LS', 'Lesoto'),
	(131, 'LV', 'Letônia'),
	(132, 'LR', 'Libéria'),
	(133, 'LI', 'Liechtenstein'),
	(134, 'LT', 'Lituânia'),
	(135, 'LU', 'Luxemburgo'),
	(136, 'LB', 'Líbano'),
	(137, 'LY', 'Líbia'),
	(138, 'MO', 'Macau, China'),
	(139, 'MK', 'Macedônia'),
	(140, 'MG', 'Madagascar'),
	(141, 'MW', 'Malauí'),
	(142, 'MV', 'Maldivas'),
	(143, 'ML', 'Mali'),
	(144, 'MT', 'Malta'),
	(145, 'MY', 'Malásia'),
	(146, 'MA', 'Marrocos'),
	(147, 'MQ', 'Martinica'),
	(148, 'MR', 'Mauritânia'),
	(149, 'MU', 'Maurício'),
	(150, 'YT', 'Mayotte'),
	(151, 'FM', 'Micronésia'),
	(152, 'MD', 'Moldávia'),
	(153, 'MN', 'Mongólia'),
	(154, 'ME', 'Montenegro'),
	(155, 'MS', 'Montserrat'),
	(156, 'MZ', 'Moçambique'),
	(157, 'MM', 'Myanmar'),
	(158, 'MX', 'México'),
	(159, 'MC', 'Mônaco'),
	(160, 'NA', 'Namíbia'),
	(161, 'NR', 'nauru'),
	(162, 'NP', 'Nepal'),
	(163, 'NI', 'Nicarágua'),
	(164, 'NG', 'Nigéria'),
	(165, 'NU', 'Niue'),
	(166, 'NO', 'Noruega'),
	(167, 'NC', 'Nova Caledônia'),
	(168, 'NZ', 'Nova Zelândia'),
	(169, 'NE', 'Níger'),
	(170, 'OM', 'Omã'),
	(171, 'PW', 'Palau'),
	(172, 'PA', 'Panamá'),
	(173, 'PG', 'Papua Nova Guiné'),
	(174, 'PK', 'Paquistão'),
	(175, 'PY', 'Paraguai'),
	(176, 'PE', 'Peru'),
	(177, 'PN', 'Pitcairn'),
	(178, 'PF', 'Polinésia Francesa'),
	(179, 'PL', 'Polônia'),
	(180, 'PR', 'Porto Rico'),
	(181, 'PT', 'Portugal'),
	(182, 'QA', 'Qatar'),
	(183, 'KG', 'Quirguistão'),
	(184, 'KE', 'Quênia'),
	(185, 'GB', 'Reino Unido'),
	(186, 'CF', 'República Central Africana'),
	(187, 'DO', 'República Dominicana'),
	(188, 'CZ', 'República Tcheca'),
	(189, 'RE', 'Reunião'),
	(190, 'RO', 'Romênia'),
	(191, 'RW', 'Ruanda'),
	(192, 'RU', 'Rússia'),
	(193, 'EH', 'Saara Ocidental'),
	(194, 'PM', 'Saint-Pierre e Miquelon'),
	(195, 'WS', 'Samoa'),
	(196, 'AS', 'Samoa Americana'),
	(197, 'SM', 'San Marino'),
	(198, 'MF', 'San Martin (parte Francesa)'),
	(199, 'SH', 'Santa Helena'),
	(200, 'LC', 'Santa Lúcia'),
	(201, 'SN', 'Senegal'),
	(202, 'SL', 'Serra Leoa'),
	(203, 'SC', 'Seychelles'),
	(204, 'SX', 'Sint Maarten'),
	(205, 'SO', 'Somália'),
	(206, 'SS', 'South Sudan'),
	(207, 'LK', 'Sri Lanka'),
	(208, 'SZ', 'Suazilândia'),
	(209, 'SD', 'Sudão'),
	(210, 'SR', 'Suriname'),
	(211, 'SE', 'Suécia'),
	(212, 'CH', 'Suíça'),
	(213, 'SJ', 'Svalbard e Jan Mayen'),
	(214, 'BL', 'São Bartolomeu'),
	(215, 'KN', 'São Kitts e Nevis'),
	(216, 'ST', 'São Tomé e Príncipe'),
	(217, 'VC', 'São Vicente e Granadinas'),
	(218, 'RS', 'Sérvia'),
	(219, 'SY', 'Síria'),
	(220, 'TJ', 'Tadjiquistão'),
	(221, 'TH', 'Tailândia'),
	(222, 'TW', 'Taiwan'),
	(223, 'TZ', 'Tanzânia'),
	(224, 'IO', 'Território Britânico do Oceano Índico'),
	(225, 'PS', 'Território Palestino'),
	(226, 'TF', 'Territórios Franceses do Sul'),
	(227, 'UM', 'Territórios Insulares dos Estados Unidos'),
	(228, 'TL', 'Timor Leste'),
	(229, 'TG', 'Togo'),
	(230, 'TO', 'tonganês'),
	(231, 'TK', 'Toquelau'),
	(232, 'TT', 'Trinidad e Tobago'),
	(233, 'TN', 'Tunísia'),
	(234, 'TM', 'Turcomenistão'),
	(235, 'TR', 'Turquia'),
	(236, 'TV', 'Tuvalu'),
	(237, 'UA', 'Ucrânia'),
	(238, 'UG', 'Uganda'),
	(239, 'UY', 'Uruguai'),
	(240, 'UZ', 'Uzbequistão'),
	(241, 'VU', 'Vanuatu'),
	(242, 'VA', 'Vaticano'),
	(243, 'VE', 'Venezuela'),
	(244, 'VN', 'Vietnã'),
	(245, 'WF', 'Wallis e Futuna'),
	(246, 'ZW', 'Zimbabue'),
	(247, 'ZM', 'Zâmbia'),
	(248, 'ZA', 'África do Sul'),
	(249, 'AT', 'Áustria'),
	(250, 'IN', 'Índia');
/*!40000 ALTER TABLE `paises` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
